services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /home/diaz/docker-data:/config
    ports:
      - 8500:80
      - 8600:443
    restart: unless-stopped
networks: {}
