version: "3.9"

services:
  wp:
    image: wordpress:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${IP}:8082:80"
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:ro
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s; timeout: 10s; retries: 3
    networks:
      - wordpress-network

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${IP}:8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: "50M"
    depends_on:
      db:
        condition: service_started
    networks:
      - wordpress-network

  db:
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${IP}:3306:3306"
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s; timeout: 10s; retries: 5
    networks:
      - wordpress-network

networks:
  wordpress-network:
    external: true
