---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Bookmarks:
    - Youtube:
        icon: youtube.svg
        href: https://youtube.com
        description: Video Platform
    - Gmail:
        icon: gmail.svg
        href: https://mail.google.com
        description: Mail Service
    - Github:
        icon: github.svg
        href: https://github.com/diazhernawan/kwf-homelab
        description: Homelab Docs
    - Open Speed Test:
        icon: openspeedtest.png
        href: "{{HOMEPAGE_VAR_OPEN-SPEED-TEST_URL}}"
        description: Internal Speed Test
    - ChatGPT:
        icon: chatgpt.svg
        href: https://chatgpt.com/
        description: OpenAI AI chatbot


- Network:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_KWF_URL}}"
        description: KWF Dream Machine Pro
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_KWF_IP}}"
            username: "{{HOMEPAGE_VAR_UNIFI_KWF_USERNAME}}"
            password: "{{HOMEPAGE_VAR_UNIFI_KWF_PASSWORD}}"
    - Pi-Hole:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        description: DNS Server
        widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE_IP}}"
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: "{{HOMEPAGE_VAR_SPEEDTEST-TRACKER_URL}}"
        description: Internet Speed
        widget:
            type: speedtest
            url: "{{HOMEPAGE_VAR_SPEEDTEST-TRACKER_IP}}"
            bitratePrecision: 1 # optional, default is 0
    - Traefik:
        icon: traefik.svg
        href: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
        description: Reverse Proxy
        widget:
            type: traefik
            url: "{{HOMEPAGE_VAR_TRAEFIK_IP}}"
            username: "{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}"
            password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"
    - NetAlertX:
        icon: netalertx.png
        href: "{{HOMEPAGE_VAR_NETALERTX_URL}}"
        description: Network Detector
        widget:
            type: netalertx
            url: "{{HOMEPAGE_VAR_NETALERTX_IP}}"   
- Management:
    - Proxmox Datacenter Manager:
        icon: proxmox.svg
        href: https://pdm.katawarna.id
        description: Proxmox Datacenter Manager
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_GALACTICA_URL}}"
        description: Galactica Cluster
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_GALACTICA_IP}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_GALACTICA_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_GALACTICA_PASSWORD}}"
            #node: Galactica
    - Portainer Galactica:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_GALACTICA_URL}}"
        description: Docker Management
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_GALACTICA_IP}}"
            env: 2
            key: "{{HOMEPAGE_VAR_PORTAINER_GALACTICA_API_KEY}}"
    - Uptime Kuma KWF:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_1_URL}}"
        description: Internal KWF Space Services
        widget:
            type: uptimekuma
            url: "{{HOMEPAGE_VAR_UPTIME_KUMA_1_IP}}"
            slug: kwf-space-services

- Home System:
    - Home Assistant:
        icon: home-assistant.svg
        href: http://10.0.1.50:8123 #"{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}"
        description: Home Assistant
        widget:
            type: homeassistant
            url: "{{HOMEPAGE_VAR_HOMEASSISTANT_IP}}"
            key: "{{HOMEPAGE_VAR_HOMEASSISTANT_API_KEY}}"
    - Immich:
        icon: immich.svg
        href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        description: photo-library
        widget:
            type: immich
            url: "{{HOMEPAGE_VAR_IMMICH_URL}}"
            key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
            version: 2

    - Tdarr Server:
        icon: tdarr.png
        href: "{{HOMEPAGE_VAR_TDARR_URL}}"
        description: Transcoder
        widget:
#            type: tdarr
#            url: "{{HOMEPAGE_VAR_TDARR_IP}}"
#            key: "{{HOMEPAGE_VAR_TDARR_KEY}}"

    - Frigate NVR:
        icon: frigate.svg
        href: "{{HOMEPAGE_VAR_FRIGATE_URL}}"
        description: AI NVR
        widget:
            type: frigate
            url: "{{HOMEPAGE_VAR_FRIGATE_IP}}"
            enableRecentEvents: false # Optional, defaults to false

- Storage:
    - TrueNAS Raptor:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_RAPTOR_URL}}"
        description: Daily NAS
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_RAPTOR_IP}}"
            key: "{{HOMEPAGE_VAR_TRUENAS_RAPTOR_API_KEY}}"
            enablePools: true # optional, defaults to false
            nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - TrueNAS Arcturus:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_ARCTURUS_URL}}"
        description: Working NAS
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_ARCTURUS_IP}}"
            key: "{{HOMEPAGE_VAR_TRUENAS_ARCTURUS_API_KEY}}"
            enablePools: true # optional, defaults to false
            nasType: core # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - TrueNAS Omega:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_OMEGA_URL}}"
        description: Archieve NAS
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_OMEGA_IP}}"
            key: "{{HOMEPAGE_VAR_TRUENAS_OMEGA_API_KEY}}"
            enablePools: true # optional, defaults to false
            nasType: core # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core

- Remote Access:
    - iDRAC R730:
        icon: idrac.svg
        href: "{{HOMEPAGE_VAR_IDRAC_1_URL}}"
        description: Dell remote KVM
    - iDRAC R510:
        icon: idrac.svg
        href: "{{HOMEPAGE_VAR_IDRAC_2_URL}}"
        description: Dell remote KVM
    - iDRAC R510 Java:
        icon: idrac.svg
        href: "{{HOMEPAGE_VAR_IDRAC6_Java_URL}}"
        description: iDRAC R510 Java KVM
    - Supermicro X10SSL IPMI:
        icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
        href: "{{HOMEPAGE_VAR_IPMI_1_URL}}"
        description: Supermicro remote KVM
    - Meshcentral:
        icon: https://pbs.twimg.com/profile_images/538050195666137088/azKzkG-M_400x400.png
        href: "{{HOMEPAGE_VAR_MESHCENTRAL_1_URL}}"
        description: Intel VPro KVM (local)
    - Meshcentral:
        icon: https://pbs.twimg.com/profile_images/538050195666137088/azKzkG-M_400x400.png
        href: "{{HOMEPAGE_VAR_MESHCENTRAL_2_URL}}"
        description: Intel VPro KVM (docker)

- Media:
    - Plex:
        icon: plex.svg
        href: "{{HOMEPAGE_VAR_PLEX_URL}}"
        description: Plex Media Server
        widget:
            type: plex
            url: "{{HOMEPAGE_VAR_PLEX_IP}}"
            key: "{{HOMEPAGE_VAR_PLEX_API_KEY}}"
    - Overseerr:
        icon: overseerr.svg
        href: "{{HOMEPAGE_VAR_OVERSEERR_URL}}"
        description: Plex Media Request
        widget:
            type: overseerr
            url: "{{HOMEPAGE_VAR_OVERSEERR_IP}}"
            key: "{{HOMEPAGE_VAR_OVERSEERR_API_KEY}}"
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Jellyfin Media Server
    - Jellyseerr:
        icon: jellyseerr.svg
        href: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
        description: Jellyfin Media Request
        #widget:
        #    type: jellyseerr
        #    url: "{{HOMEPAGE_VAR_JELLYSEERR_IP}}"
        #    key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"

- Downloader:
    - SABnzbd Arr:
        icon: sabnzbd-alt.svg
        href: "{{HOMEPAGE_VAR_SABNZBD_1_URL}}"
        description: Usenet Downloader
        widget:
            type: sabnzbd
            url: "{{HOMEPAGE_VAR_SABNZBD_1_IP}}"
            key: "{{HOMEPAGE_VAR_SABNZBD_1_API_KEY}}"
    - qBittorrent Arr:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QBITTORRENT_1_URL}}"
        description: qBittorrent Downloader
        widget:
            type: qbittorrent
            url: "{{HOMEPAGE_VAR_QBITTORRENT_1_IP}}"
            username: "{{HOMEPAGE_VAR_QBITTORRENT_1_USERNAME}}"
            password: "{{HOMEPAGE_VAR_QBITTORRENT_1_PASSWORD}}"
    - Deluge Games:
        icon: deluge.svg
        href: "{{HOMEPAGE_VAR_DELUGE_URL}}"
        description: Deluge Torrent Downloader
        widget:
            type: deluge
            url: "{{HOMEPAGE_VAR_DELUGE_IP}}"
            password: "{{HOMEPAGE_VAR_DELUGE_PASSWORD}}"

- Servarr:
    - Prowlarr:
        icon: prowlarr.svg
        href: "{{HOMEPAGE_VAR_PROWLARR_1_URL}}"
        description: Indexer Manager
        widget:
            type: prowlarr
            url: "{{HOMEPAGE_VAR_PROWLARR_1_IP}}"
            key: "{{HOMEPAGE_VAR_PROWLARR_1_API_KEY}}"
    - Radarr:
        icon: radarr.svg
        href: "{{HOMEPAGE_VAR_RADARR_1_URL}}"
        description: PVR for Movies
        widget:
            type: radarr
            url: "{{HOMEPAGE_VAR_RADARR_1_IP}}"
            key: "{{HOMEPAGE_VAR_RADARR_1_API_KEY}}"
    - Sonarr:
        icon: sonarr.svg
        href: "{{HOMEPAGE_VAR_SONARR_1_URL}}"
        description: PVR for TV Shows
        widget:
            type: sonarr
            url: "{{HOMEPAGE_VAR_SONARR_1_IP}}"
            key: "{{HOMEPAGE_VAR_SONARR_1_API_KEY}}"
    - Bazarr:
        icon: bazarr.svg
        href: "{{HOMEPAGE_VAR_BAZARR_1_URL}}"
        description: Subtitle Manager

- Stash:
    - Prowlarr Stash:
        icon: prowlarr.svg
        href: "{{HOMEPAGE_VAR_PROWLARR_2_URL}}"
        description: Indexer Manager
        widget:
            type: prowlarr
            url: "{{HOMEPAGE_VAR_PROWLARR_2_IP}}"
            key: 517d2650fa8a4e9d8c7f3ba58b419313
    - JDownloader2 Stash:
        icon: jdownloader2.png
        href: "{{HOMEPAGE_VAR_JDOWNLOADER2_URL}}"
        description: JDownloader2
    - qBittorrent Stash:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QBITTORRENT_2_URL}}"
        description: qBittorrent Downloader
        widget:
            type: qbittorrent
            url: "{{HOMEPAGE_VAR_QBITTORRENT_2_IP}}"
            username: "{{HOMEPAGE_VAR_QBITTORRENT_2_USERNAME}}"
            password: "{{HOMEPAGE_VAR_QBITTORRENT_2_PASSWOR}}"

- BBF Machines:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_BBF_URL}}"
        description: BBF unifi network controller
        widget:
            type: unifi
            url: "{{HOMEPAGE_VAR_UNIFI_BBF_IP}}"
            username: "{{HOMEPAGE_VAR_UNIFI_BBF_USERNAME}}"
            password: "{{HOMEPAGE_VAR_UNIFI_BBF_PASSWORD}}"
    - Proxmox BBF Main Server:
        icon: proxmox.svg
        href: https://10.10.10.150:8006 #"{{HOMEPAGE_VAR_PROXMOX_BBF-MAIN-SERVER_URL}}"
        description: BBF Main Server
        widget:
            type: proxmox
            url: https://10.10.10.150:8006 #"{{HOMEPAGE_VAR_PROXMOX_BBF-MAIN-SERVER_IP}}"
            username: api@pam!homepage #"{{HOMEPAGE_VAR_PROXMOX_BBF-MAIN-SERVER_USER}}"
            password: 9a25e9a8-406a-4805-b70f-c8292e9808eb #"{{HOMEPAGE_VAR_PROXMOX_BBF-MAIN-SERVER_PASSWORD}}"
            #node: BBF Main Server
    - TrueNAS BBF:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_TAURINE_URL}}"
        description: Truenas scale
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_TAURINE_IP}}"
            key: "{{HOMEPAGE_VAR_TRUENAS_TAURINE_API_KEY}}"
    - Portainer BBF:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_BBF_URL}}"
        description: Docker Management
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_BBF_IP}}"
            env: 2
            key: "{{HOMEPAGE_VAR_PORTAINER_BBF_API_KEY}}"
#    - Uptime Kuma BBF:
#        icon: uptime-kuma.svg
#        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_2_URL}}"
#        description: External BBF Services
#        widget:
#            type: uptimekuma
#            url: "{{HOMEPAGE_VAR_UPTIME_KUMA_2_IP}}"
#            slug: bbf-services


