---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- unifi_console:
    url: https://10.0.0.1
    username: homepage-monitor
    password: ALEXAdragon18