######FRIGATE-CONFIG-22APRIL2024######

mqtt:
  enabled: true
  host: 10.10.50.9
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: mqtt

######DETECTORS&NVR######

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 2
    post_capture: 3
    retain:
      default: 7
      mode: active_objects
    objects:
      - person
      - car

detect:
  fps: 25
  width: 704
  height: 576
  enabled: true
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
  annotation_offset: 0

objects:
  track:
    - person
    - car

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10

######TELEMETRY######

telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo

  stats:
    intel_gpu_stats: true
    network_bandwidth: true

  version_check: true

######go2rtc######

go2rtc:
  streams:
    Carport_Depan:
      - rtsp://admin:brabus18@10.10.50.200:554/cam/realmonitor?channel=1subtype=0
    Carport_Depan_sub:
      - rtsp://admin:brabus18@10.10.50.200:554/cam/realmonitor?channel=1subtype=1
    Carport_Samping:
      - rtsp://admin:brabus18@10.10.50.205:554/cam/realmonitor?channel=1subtype=0
    Carport_Samping_sub:
      - rtsp://admin:brabus18@10.10.50.205:554/cam/realmonitor?channel=1subtype=1
    Taman_Belakang:
      - rtsp://admin:brabus18@10.10.50.210:554/cam/realmonitor?channel=1subtype=0
    Taman_Belakang_sub:
      - rtsp://admin:brabus18@10.10.50.210:554/cam/realmonitor?channel=1subtype=1
    Office:
      - ffmpeg:rtsp://10.10.50.215:554/user=admin_password=MH3DeRW6_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac
    Office_sub:
      - ffmpeg:rtsp://10.10.50.215:554/user=admin_password=MH3DeRW6_channel=1_stream=1&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac

  webrtc:
    candidates:
      - 10.10.50.16:8555
      - stun:8555

######CAMERAS######

cameras:
  Carport_Depan:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.10.50.16:8554/Carport_Depan
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.10.50.16:8554/Carport_Depan_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    webui_url: 10.10.50.200

  Carport_Samping:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.10.50.16:8554/Carport_Samping
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.10.50.16:8554/Carport_Samping_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    webui_url: 10.10.50.205

    motion:
      mask:
        - 0.402,0.362,0.426,0.196,0.514,0.204,0.514,0.411
        - 0.252,0.601,0.452,0.666,0.436,0.998,0,1,0,0.916,0.113,0.66
  Taman_Belakang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.10.50.16:8554/Taman_Belakang
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.10.50.16:8554/Taman_Belakang_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    webui_url: 10.10.50.210

  Office:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://10.10.50.16:8554/Office
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://10.10.50.16:8554/Office_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    webui_url: 10.10.50.215

version: 0.14
