services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Jakarta
    ports:
      - "5055:5055" # Adjusted port
    volumes:
      - ./jellyseerr:/app/config
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./overseerr:/config
    ports:
      - "5500:5055"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - 1_storage:/1_storage
    ports:
      - "7878:7878"
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:7878 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - 1_storage:/1_storage
    ports:
      - "8989:8989"
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8989 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ./6_bazarr:/config
      - 1_storage:/1_storage
    ports:
      - "6767:6767"
    restart: unless-stopped

networks:
  portainer_default:
    external: true

volumes:
  1_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/smb/Raptor/1_storage
